### ISSUE TITLE
Setting differential_subset_to_contrast_samples: true with output from nfcore rnaseq causes error

### ISSUE THREAD

**Issue by aghr** [nf-core/differentialabundance#234]
### Description of the bug

I apply the nfcore diffabundance pipeline on the output of the nfcore rnaseq pipeline on bulk RNA-seq data. The data contains >2 conditions with several replicates per condition. That's why I want to invoke the diffabundance pipeline with parameter differential_subset_to_contrast_samples: true . The pipeline crashes with several errors when invoking it with differential_subset_to_contrast_samples: true , whereas it runs with success with differential_subset_to_contrast_samples: false. 

My guess on this error is that the samplesheet.csv contains all samples across >2 conditions. Setting differential_subset_to_contrast_samples: true will run a DESeq2 analysis for each contrast comparing two conditions. There are several contrasts and the output for each run will contain data only for the samples of the two conditions of the contrast. not for all samples in samplesheet.csv. It can be that later when running the GSEA on the output of each DESeq2 analysis individually GSEA also reads in the samplesheet.csv and expects all samples of the sample sheet to be contained in the output of the DESeq2 analyses but this is not the case when setting differential_subset_to_contrast_samples: true .

### Command used and terminal output

```console
nextflow run nf-core/differentialabundance -r 1.4.0 \
    -params-file params.yml -c local.config \
    --input samplesheet.csv \
    --contrasts contrasts.csv \
    --outdir ./ \
    --gtf /XXX/XXX/output/workflow/genome/Mus_musculus.GRCm39.111.gtf.gz \
    --study_type rnaseq \
    --study_abundance_type counts --gsea_gene_sets /XXX/XXX/output/workflow/gene_sets/mh.all.v2023.2.Mm.symbols.gmt


local.config:
#####################
process{
  executor='local'
  cpu=20
  memory='250 GB'
}


singularity{
  enabled=true
}

conda{
  enabled=false
}
##################


params.yml:
#################
differential_feature_id_column: gene_id
differential_min_fold_change: -10000000
differential_max_pval: 2
differential_max_qval: 0.05
differential_feature_name_column: gene_name
differential_foldchanges_logged: true
# Setting this to false makes workflow to run with success
differential_subset_to_contrast_samples: true
deseq2_test: Wald
deseq2_fit_type: local
deseq2_sf_type: ratio
deseq2_min_replicates_for_replace: 7
deseq2_use_t: false
deseq2_independent_filtering: true
deseq2_lfc_threshold: 2
deseq2_alt_hypothesis: greaterAbs
deseq2_p_adjust_method: fdr
deseq2_alpha: 0.1
deseq2_minmu: 0.5
deseq2_vs_method: vst
deseq2_vst_nsub: 3000
deseq2_shrink_lfc: true
deseq2_vs_blind: true
gsea_run: true
gsea_permute: phenotype
gsea_nperm: 1000
gsea_scoring_scheme: weighted
gsea_metric: Signal2Noise
gsea_sort: real
gsea_order: descending
gsea_set_max: 1000
gsea_set_min: 10
gsea_norm: meandiv
gsea_rnd_type: no_balance
gsea_make_sets: true
gsea_median: false
gsea_num: 100
gsea_plot_top_x: 50
gsea_rnd_seed: '42'
gsea_save_rnd_lists: false
gsea_zip_report: true
#################
```

### Relevant files

Excerpt from .nextflow.log
########################

Feb-16 12:54:50.105 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 24; name: NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (loop_vs_wt_e115); status: COMPLETED; exit: 1; error: -; workDir: /XXX/XXX/output/workflow/work/d1/4066eaca337f5ccd8c02578e84f7d8]
Feb-16 12:54:50.112 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (loop_vs_wt_e115); work-dir=/XXX/XXX/output/workflow/work/d1/4066eaca337f5ccd8c02578e84f7d8
  error [nextflow.exception.ProcessFailedException]: Process `NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (loop_vs_wt_e115)` terminated with an error exit status (1)
Feb-16 12:54:50.139 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (loop_vs_wt_e115)'

Caused by:
  Process `NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (loop_vs_wt_e115)` terminated with an error exit status (1)

Command executed:

  # Run GSEA

  gsea-cli GSEA \
      -res loop_vs_wt_e135.gct \
      -cls loop_vs_wt_e115.cls#loop_e115_versus_wtloop_e115 \
      -gmx mh.all.v2023.2.Mm.symbols.gmt \
      -chip Mus_musculus.anno.feature_metadata.chip -collapse true \
      -out . \
      --rpt_label loop_vs_wt_e115.mh.all.v2023.2.Mm.symbols \
      -nperm 1000 -permute phenotype -scoring_scheme weighted -metric Signal2Noise -sort real -order descending -set_max 1000 -set_min 10 -norm meandiv -rnd_type no_balance -make_sets true -median false -num 100 -plot_top_x 50 -rnd_seed 42 -save_rnd_lists false -zip_report true

  # Un-timestamp the outputs for path consistency
  mv loop_vs_wt_e115.mh.all.v2023.2.Mm.symbols.Gsea.*/* .
  timestamp=$(cat *.rpt | grep producer_timestamp | awk '{print $2}')

  for pattern in _${timestamp} .${timestamp}; do
      find . -name "*${pattern}*" | sed "s|^\./||" | while read -r f; do
          mv $f ${f//$pattern/}
      done
  done
  sed -i.bak "s/[_\.]$timestamp//g" *.rpt *.html && rm *.bak

  # Prefix files that currently lack it
  ls -p | grep -v / | grep -v "loop_vs_wt_e115.mh.all.v2023.2.Mm.symbols." | while read -r f; do
      mv $f loop_vs_wt_e115.mh.all.v2023.2.Mm.symbols.${f}
      sed -i.bak "s/$f/loop_vs_wt_e115.mh.all.v2023.2.Mm.symbols.${f}/g" *.rpt *.html && rm *.bak
  done

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA":
      gsea: 4.3.2
  END_VERSIONS

Command exit status:
  1
Command output:
  Using system JDK.
  [1708084486368] [INFO] Parameters passed to GSEA tool:
  [1708084486490] [INFO] gmx    mh.all.v2023.2.Mm.symbols.gmt
  [1708084486490] [INFO] res    loop_vs_wt_e135.gct
  [1708084486490] [INFO] cls    loop_vs_wt_e115.cls#loop_e115_versus_wtloop_e115
  [1708084486491] [INFO] rnd_seed       42
  [1708084486491] [INFO] rpt_label      loop_vs_wt_e115.mh.all.v2023.2.Mm.symbols
  [1708084486491] [INFO] collapse       true
  [1708084486492] [INFO] zip_report     true
  [1708084486492] [INFO] gui    false
  [1708084486492] [INFO] out    .
  [1708084486493] [INFO] chip   Mus_musculus.anno.feature_metadata.chip
  [1708084486493] [INFO] norm   meandiv
  [1708084486493] [INFO] nperm  1000
  [1708084486494] [INFO] permute        phenotype
  [1708084486494] [INFO] rnd_type       no_balance
  [1708084486494] [INFO] scoring_scheme weighted
  [1708084486495] [INFO] metric Signal2Noise
  [1708084486495] [INFO] sort   real
  [1708084486495] [INFO] order  descending
  [1708084486496] [INFO] make_sets      true
  [1708084486496] [INFO] median false
  [1708084486496] [INFO] num    100
  [1708084486497] [INFO] plot_top_x     50
  [1708084486497] [INFO] rnd_seed       42
  [1708084486497] [INFO] save_rnd_lists false
  [1708084486498] [INFO] set_max        1000
  [1708084486498] [INFO] set_min        10
  [1708084486549] [INFO] Made Vdb dir JIT: feb16
  [1708084486577] [WARNING] Couldn't create user preferences directory. User preferences are unusable.
                                                                                                               445,3         77%

  [1708084486580] [WARNING] java.io.IOException: No such file or directory
  [1708084486597] [INFO] Begun importing: Dataset from: loop_vs_wt_e135.gct
  # of elements = 1
  loop_vs_wt_e115.cls#loop_e115_versus_wtloop_e115
  [1708084488043] [INFO] Begun importing: Template from: loop_vs_wt_e115.cls
  to parse>mh.all.v2023.2.Mm.symbols.gmt< got: [mh.all.v2023.2.Mm.symbols.gmt]
  [1708084488071] [INFO] Begun importing: GeneSetMatrix from: mh.all.v2023.2.Mm.symbols.gmt
  [1708084488089] [INFO] Using file 'mh.all.v2023.2.Mm.symbols.gmt' with unknown version
  [1708084488092] [INFO] Begun importing: Chip from: Mus_musculus.anno.feature_metadata.chip
  [1708084488177] [INFO] Parsed from dotchip : 57180
  [1708084488296] [INFO] Creating collapsed dataset loop_vs_wt_e135_collapsed_to_symbols, chosen mode 0
  [1708084488297] [INFO] Collapsing dataset was done. Original: 24182x6 (ann: 24182,6,Mus_musculus.anno.feature_metadata.chip) collapsed: 23988x6 (ann: 23988,6,Mus_musculus.anno.feature_metadata.chip)
  [1708084488379] [INFO] Extracting ds: loop_vs_wt_e135_collapsed_to_symbols by template: loop_vs_wt_e115.cls#loop_e115_versus_wtloop_e115
  [1708084488408] [INFO] Renaming rpt dir on error to: ./error_loop_vs_wt_e115.mh.all.v2023.2.Mm.symbols.Gsea.1708084488014

Command error:
  [1708084486491] [INFO] rpt_label      loop_vs_wt_e115.mh.all.v2023.2.Mm.symbols
  [1708084486491] [INFO] collapse       true
  [1708084486492] [INFO] zip_report     true
  [1708084486492] [INFO] gui    false
  [1708084486492] [INFO] out    .
  [1708084486493] [INFO] chip   Mus_musculus.anno.feature_metadata.chip
  [1708084486493] [INFO] norm   meandiv
  [1708084486493] [INFO] nperm  1000
  [1708084486494] [INFO] permute        phenotype
  [1708084486494] [INFO] rnd_type       no_balance
  [1708084486494] [INFO] scoring_scheme weighted
  [1708084486495] [INFO] metric Signal2Noise
  [1708084486495] [INFO] sort   real
  [1708084486495] [INFO] order  descending
  [1708084486496] [INFO] make_sets      true
  [1708084486496] [INFO] median false
  [1708084486496] [INFO] num    100
  [1708084486497] [INFO] plot_top_x     50
  [1708084486497] [INFO] rnd_seed       42
  [1708084486497] [INFO] save_rnd_lists false
  [1708084486498] [INFO] set_max        1000
  [1708084486498] [INFO] set_min        10
  [1708084486549] [INFO] Made Vdb dir JIT: feb16
  [1708084486577] [WARNING] Couldn't create user preferences directory. User preferences are unusable.
  [1708084486580] [WARNING] java.io.IOException: No such file or directory
  [1708084486597] [INFO] Begun importing: Dataset from: loop_vs_wt_e135.gct
  # of elements = 1
  loop_vs_wt_e115.cls#loop_e115_versus_wtloop_e115
  [1708084488043] [INFO] Begun importing: Template from: loop_vs_wt_e115.cls
  to parse>mh.all.v2023.2.Mm.symbols.gmt< got: [mh.all.v2023.2.Mm.symbols.gmt]
  [1708084488071] [INFO] Begun importing: GeneSetMatrix from: mh.all.v2023.2.Mm.symbols.gmt
  [1708084488089] [INFO] Using file 'mh.all.v2023.2.Mm.symbols.gmt' with unknown version
  [1708084488092] [INFO] Begun importing: Chip from: Mus_musculus.anno.feature_metadata.chip
  [1708084488177] [INFO] Parsed from dotchip : 57180
  [1708084488296] [INFO] Creating collapsed dataset loop_vs_wt_e135_collapsed_to_symbols, chosen mode 0
  [1708084488297] [INFO] Collapsing dataset was done. Original: 24182x6 (ann: 24182,6,Mus_musculus.anno.feature_metadata.chip) collapsed: 23988x6 (ann: 23988,6,Mus_musculus.anno.feature_metadata.chip)
  [1708084488379] [INFO] Extracting ds: loop_vs_wt_e135_collapsed_to_symbols by template: loop_vs_wt_e115.cls#loop_e115_versus_wtloop_e115
  java.lang.ArrayIndexOutOfBoundsException: col:30 > matrix's fColCnt:6
        at org.gsea_msigdb.gsea/edu.mit.broad.genome.math.Matrix.getColumnV(Matrix.java:261)
        at org.gsea_msigdb.gsea/edu.mit.broad.genome.objects.DefaultDataset.getColumn(DefaultDataset.java:289)
       at org.gsea_msigdb.gsea/edu.mit.broad.genome.objects.TemplateFactory.extract(TemplateFactory.java:85)
        at org.gsea_msigdb.gsea/edu.mit.broad.genome.alg.DatasetGenerators.extract(DatasetGenerators.java:292)
        at org.gsea_msigdb.gsea/edu.mit.broad.genome.alg.DatasetGenerators.extract(DatasetGenerators.java:288)
        at org.gsea_msigdb.gsea/xtools.gsea.AbstractGsea2Tool.execute_one(AbstractGsea2Tool.java:79)
        at org.gsea_msigdb.gsea/xtools.gsea.AbstractGsea2Tool.execute_one_with_reporting(AbstractGsea2Tool.java:103)
        at org.gsea_msigdb.gsea/xtools.gsea.Gsea.execute(Gsea.java:166)
        at org.gsea_msigdb.gsea/xtools.api.AbstractTool.module_main(AbstractTool.java:401)
        at org.gsea_msigdb.gsea/org.genepattern.modules.GseaWrapper.main(GseaWrapper.java:291)
        at org.gsea_msigdb.gsea/xapps.gsea.CLI.main(CLI.java:29)
  [1708084488408] [INFO] Renaming rpt dir on error to: ./error_loop_vs_wt_e115.mh.all.v2023.2.Mm.symbols.Gsea.1708084488014

Work dir:
  /XXX/XXX/output/workflow/work/d1/4066eaca337f5ccd8c02578e84f7d8

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
Feb-16 12:54:50.147 [Task monitor] INFO  nextflow.Session - Execution cancelled -- Finishing pending tasks before exit
Feb-16 12:54:50.183 [main] DEBUG nextflow.Session - Session await > all processes finished
Feb-16 12:54:50.185 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 22; name: NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (inv_vs_wt_e125); status: COMPLETED; exit: 1; error: -; workDir: /XXX/XXX/output/workflow/work/f8/e014b5add0e042e4c5a6962151379e]
Feb-16 12:54:50.185 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (inv_vs_wt_e125); work-dir=/XXX/XXX/output/workflow/work/f8/e014b5add0e042e4c5a6962151379e
  error [nextflow.exception.ProcessFailedException]: Process `NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (inv_vs_wt_e125)` terminated with an error exit status (1)
Feb-16 12:54:50.186 [Actor Thread 21] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:RMARKDOWNNOTEBOOK; work-dir=null
  error [java.lang.InterruptedException]: java.lang.InterruptedException
                                Feb-16 12:54:50.190 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 21; name: NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (loop_vs_wt_e125); status: COMPLETED; exit: 1; error: -; workDir: /XXX/XXX/output/workflow/work/0d/ed7a8ba1a40875e9e363aca7f0b884]
Feb-16 12:54:50.191 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (loop_vs_wt_e125); work-dir=/XXX/XXX/output/workflow/work/0d/ed7a8ba1a40875e9e363aca7f0b884
  error [nextflow.exception.ProcessFailedException]: Process `NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (loop_vs_wt_e125)` terminated with an error exit status (1)
Feb-16 12:54:50.191 [Actor Thread 29] DEBUG nextflow.file.FileCollector - Deleting file collector temp dir: /tmp/nxf-173997325202795786
Feb-16 12:54:50.195 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 23; name: NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (inv_vs_wt_e135); status: COMPLETED; exit: 1; error: -; workDir: /XXX/XXX/output/workflow/work/0f/b8b5e11d87680d95e935b465cc1550]
Feb-16 12:54:50.195 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (inv_vs_wt_e135); work-dir=/XXX/XXX/output/workflow/work/0f/b8b5e11d87680d95e935b465cc1550
  error [nextflow.exception.ProcessFailedException]: Process `NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (inv_vs_wt_e135)` terminated with an error exit status (1)
Feb-16 12:54:50.211 [Actor Thread 36] DEBUG nextflow.sort.BigSort - Sort completed -- entries: 7; slices: 1; internal sort time: 0.022 s; external sort time: 0.002 s; total time: 0.024 s
Feb-16 12:54:50.222 [Actor Thread 36] DEBUG nextflow.file.FileCollector - Saved collect-files list to: /XXX/XXX/output/workflow/work/collect-file/a0e32014125d264c06fdb3864c98f054
Feb-16 12:54:50.231 [Actor Thread 36] DEBUG nextflow.file.FileCollector - Deleting file collector temp dir: /tmp/nxf-8002081208300576428
Feb-16 12:54:50.248 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 25; name: NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (loop_vs_wt_e135); status: COMPLETED; exit: 1; error: -; workDir: /XXX/XXX/output/workflow/work/25/fdb2744533edd1885e5d295430fd17]
Feb-16 12:54:50.248 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (loop_vs_wt_e135); work-dir=/XXX/XXX/output/workflow/work/25/fdb2744533edd1885e5d295430fd17
@                                            error [nextflow.exception.ProcessFailedException]: Process `NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GSEA_GSEA (loop_vs_wt_e135)` terminated with an error exit status (1)
Feb-16 12:54:55.869 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 20; name: NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:PLOT_EXPLORATORY (condition); status: COMPLETED; exit: 1; error: -; workDir: /XXX/XXX/output/workflow/work/35/15b254f67de962bd2a30119d28fa04]
Feb-16 12:54:55.870 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:PLOT_EXPLORATORY (condition); work-dir=/XXX/XXX/output/workflow/work/35/15b254f67de962bd2a30119d28fa04
  error [nextflow.exception.ProcessFailedException]: Process `NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:PLOT_EXPLORATORY (condition)` terminated with an error exit status (1)
Feb-16 12:54:59.187 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 16; name: NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:DESEQ2_DIFFERENTIAL ([id:inv_vs_wt_e125, variable:condition, reference:wtinv_e125, target:inv_e125, blocking:]); status: COMPLETED; exit: 0; error: -; workDir: /XXX/XXX/output/workflow/work/a4/da4d864c8b74d80640091386c57c4e]
Feb-16 12:54:59.219 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Process NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:DESEQ2_DIFFERENTIAL > Skipping output binding because one or more optional files are missing: fileoutparam<5:1>
Feb-16 12:55:01.812 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 19; name: NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:PLOT_DIFFERENTIAL (loop_vs_wt_e125); status: COMPLETED; exit: 0; error: -; workDir: /XXX/XXX/output/workflow/work/06/3b88df1f289283881b4c884e53d0ff]
Feb-16 12:55:01.827 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Process NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:PLOT_DIFFERENTIAL > Skipping output binding because one or more optional files are missing: fileoutparam<1:1>
Feb-16 12:55:02.403 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 18; name: NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:PLOT_DIFFERENTIAL (loop_vs_wt_e115); status: COMPLETED; exit: 0; error: -; workDir: /XXX/XXX/output/workflow/work/eb/299f44d5163890210f3e5e37d04dcb]

Feb-16 12:55:11.713 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Process NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:DESEQ2_DIFFERENTIAL > Skipping output binding because one or more optional files are missing: fileoutparam<5:1>
Feb-16 12:55:11.720 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local) - terminating tasks monitor poll loop
Feb-16 12:55:11.720 [main] DEBUG nextflow.Session - Session await > all barriers passed
Feb-16 12:55:11.783 [main] DEBUG nextflow.util.ThreadPoolManager - Thread pool 'PublishDir' shutdown completed (hard=false)
Feb-16 12:55:11.828 [main] INFO  nextflow.Nextflow - -^[[0;35m[nf-core/differentialabundance]^[[0;31m Pipeline completed with errors^[[0m-
Feb-16 12:55:11.835 [main] DEBUG n.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=20; failedCount=6; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=37m 26s; failedDuration=35.8s; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=11; peakCpus=36; peakMemory=82 GB; ]
Feb-16 12:55:11.835 [main] DEBUG nextflow.trace.TraceFileObserver - Workflow completed -- saving trace file
Feb-16 12:55:11.838 [main] DEBUG nextflow.trace.ReportObserver - Workflow completed -- rendering execution report
Feb-16 12:55:12.541 [main] DEBUG nextflow.trace.TimelineObserver - Workflow completed -- rendering execution timeline
Feb-16 12:55:12.807 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Feb-16 12:55:12.807 [main] INFO  org.pf4j.AbstractPluginManager - Stop plugin 'nf-validation@1.1.3'
Feb-16 12:55:12.807 [main] DEBUG nextflow.plugin.BasePlugin - Plugin stopped nf-validation
Feb-16 12:55:12.822 [main] DEBUG nextflow.util.ThreadPoolManager - Thread pool 'FileTransfer' shutdown completed (hard=false)
Feb-16 12:55:12.822 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
~                                                                                               

### System information

nextflow version 23.10.1.5891
nf-core/differentialabundance v1.4.0-ga3d664c
Hardware: Desktop
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.7.1908 (Core)
Release:        7.7.1908
Codename:       Core
Executor: local
Container: Singularity

**Comment by jenmuell** [comment]
I tried to fix this bug and **could not recreate it on the dev or master branch**. Therefore, I want to make sure, if I understood the problem correctly:
- We assume a condition (treatment) with multiple different states (H20, drug1, drug2)
- In the contrast sheet we are only interested in the comparison H20 vs drug1  and H20 vs drug2 but _not_ drug1 vs drug2
- The parameter _differential_subset_to_contrast_samples_ will be set to _true_, which will remove all samples, which are not part of any comparison in the contrast sheet

**Comment by pinin4fjords** [comment]
This issue has not had any activity since @jenmuell tried to assist in March having failed to replicate (thank you @jenmuell !). 

Closing for now, but @aghr feel free to reopen if you can reproduce the error on `dev` and provide us with enough information to do so.

**Comment by grst** [comment]
> Closing for now

closing for real now

**Comment by Gregory-Schwing-MD-PhD** [comment]
I encountered a similar problem in my code, which i can add more data to reproduce if necessary, but I figured out setting subsetting to false corrected my pipeline.  This is a dangerous though because at least from Google Gemini, this option should only affect speed of execution and not ability to run without error.

ERROR ~ Error executing process > 'NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:PLOT_EXPLORATORY (Environment)'

Caused by:
  Process `NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:PLOT_EXPLORATORY (Environment)` terminated with an error exit status (1)


Command executed:

  exploratory_plots.R \
      --sample_metadata "metadata.sample_metadata.tsv" \
      --feature_metadata "GRCh38.anno.feature_metadata.tsv" \
      --assay_files "salmon.merged.gene_counts.assay.tsv,all.normalised_counts.tsv,all.vst.tsv" \
      --contrast_variable "Environment" \
      --outdir "Environment" \
      --sample_id_col "sample" --feature_id_col "gene_id" --assay_names "raw,normalised,variance_stabilised" --final_assay "variance_stabilised" --outlier_mad_threshold -5 --palette_name "Set1" --log2_assays "raw,normalised"

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:PLOT_EXPLORATORY":
      r-shinyngs: $(Rscript -e "library(shinyngs); cat(as.character(packageVersion('shinyngs')))")
  END_VERSIONS

Command exit status:
  1

Command output:
  [1] "Reading inputs..."

Command error:
      table, tapply, union, unique, unsplit, which.max, which.min

  Loading required package: S4Vectors

  Attaching package: ‘S4Vectors’

  The following object is masked from ‘package:utils’:

      findMatches

  The following objects are masked from ‘package:base’:

      expand.grid, I, unname

  Loading required package: IRanges
  Loading required package: GenomeInfoDb
  Loading required package: Biobase
  Welcome to Bioconductor

      Vignettes contain introductory material; view with
      'browseVignettes()'. To cite Bioconductor, see
      'citation("Biobase")', and for packages 'citation("pkgname")'.


  Attaching package: ‘Biobase’

  The following object is masked from ‘package:MatrixGenerics’:

      rowMedians

  The following objects are masked from ‘package:matrixStats’:

      anyMissing, rowMedians


  Attaching package: ‘shinyngs’

  The following object is masked from ‘package:MatrixGenerics’:

      colMedians

  The following object is masked from ‘package:matrixStats’:

      colMedians

  Error in h(simpleError(msg, call)) :
    error in evaluating the argument 'object' in selecting a method for function 'na.omit': Some sample metadata names (NL70B,NL71B) are absent from the matrix in all.normalised_counts.tsv, columns are: C2B,IL67B,IL68B,IL69B
  Calls: lapply -> lapply -> FUN -> na.omit -> read_matrix
  Execution halted
  INFO:    Cleaning up image...

Work dir:
  /wsu/home/go/go24/go2432/u251-transcriptomic-evolution/work/75/0a4e0acef1b82d01d6afab21220f2f

Container:
  /wsu/home/go/go24/go2432/singularity_cache/depot.galaxyproject.org-singularity-r-shinyngs-1.8.8--r43hdfd78af_0.img

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
Execution cancelled -- Finishing pending tasks before exit

<img width="1024" height="559" alt="Image" src="https://github.com/user-attachments/assets/f12e93f0-6c14-47dc-8f8a-c02326588084" />
